language: php

php:
- 5.5

env:
- DB=mysql

before_script:
- composer install --dev
- composer selfupdate
- pyrus install --force phpunit/DbUnit
- phpenv rehash

- mysql -e "CREATE DATABASE IF NOT EXISTS resttestdb;" -uroot;
- mysql -e "CREATE TABLE IF NOT EXISTS resttestdb.todo (id int(11) NOT NULL AUTO_INCREMENT, name varchar(255) NOT NULL, created datetime NOT NULL, PRIMARY KEY (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8;" -uroot;

script: phpunit -c app/