language: php

php:
  - 5.5

env:
  - DB=mysql

before_script:
  - composer install --dev
  - pyrus install --force phpunit/DbUnit
  - phpenv rehash
  - mysql -e "CREATE DATABASE IF NOT EXISTS resttestdb;" -uroot;
  - mysql -e "CREATE TABLE IF NOT EXISTS resttestdb.todo (id int(11) NOT NULL AUTO_INCREMENT, name varchar(255) NOT NULL, created datetime NOT NULL, PRIMARY KEY (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8;" -uroot;
  - mysql -e "INSERT INTO resttestdb.todo VALUES (null, 'Download silex-skeleton-rest.', '2013-01-01 00:00:00'), (null, 'Utilize the skeleton so I can use it for my project.', '2013-01-06 19:00:00');" -uroot;
  - mysql -e "CREATE TABLE IF NOT EXISTS `resttestdb`.`user` (`id` int(11) NOT NULL AUTO_INCREMENT, `name` varchar(255) DEFAULT NULL, `surname` varchar(255) DEFAULT NULL, `email` varchar(255) DEFAULT NULL, `employee_nr` varchar(255) DEFAULT NULL, `role` tinyint(4) NOT NULL DEFAULT '0', `password` varchar(255) DEFAULT NULL, `salt` varchar(255) DEFAULT NULL, `locked` tinyint(4) NOT NULL DEFAULT '0', `deleted` tinyint(4) NOT NULL DEFAULT '0', `created_by` varchar(255) DEFAULT NULL, `created_at` char(20) DEFAULT NULL, `updated_by` varchar(255) DEFAULT NULL, `updated_at` char(20) DEFAULT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8;" -uroot;
  - mysql -e "INSERT INTO `resttestdb`.`user` VALUES(null, 'test_user_name', 'test_user_surname', 'test_user_name@email.com', 'test_user_employee_nr', '0', 'test_user_password', 'test_user_salt', '0', '0', 'test_user_created_by', '2013-01-01 00:00:00', 'test_user_updated_by', '2013-01-01 00:00:00'), (null, 'test_user_name_2', 'test_user_surname_2', 'test_user_name_2@email.com', 'test_user_employee_nr_2', '0', 'test_user_password_2', 'test_user_salt_2', '0', '0', 'test_user_created_by', '2013-01-01 00:00:00', 'test_user_updated_by', '2013-01-01 00:00:00');" -uroot;

script: phpunit -c app/
